# Generated by Django 4.2.3 on 2024-10-17 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("image", models.ImageField(upload_to="img/")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="news",
                        to="news.user",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="news", to="news.category"
                    ),
                ),
            ],
        ),
    ]
