# Generated by Django 4.2.3 on 2024-10-17 17:35

from django.db import migrations, models
import news.validators


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_alter_news_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateTimeField(
                validators=[news.validators.validate_date_format]
            ),
        ),
    ]
